config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  concern :card_owner do
    resources :cards, except: [:edit, :update]
  end

  resources :articles, except: [:edit]
  resources :locations
  resources :payments, only: [:index]
  resources :points
  resources :positions, except: [:edit]
  resource :session, path: 'login', except: [:show, :new, :edit] do
    get '/', action: 'new', on: :collection, as: :new
  end
  resources :shows, shallow: true do
    resources :attendees, controller: 'users'
    resources :staffs
    resources :booths, shallow: true do
      resources :fees, only: [:new, :create, :destroy]
      resources :payments, except: [:index, :edit] do
        post 'pay', on: :member
      end
      get 'addons', on: :member
      get 'billing', on: :member
      get ':door', action: 'door', door: /[0-9A-Z]/, on: :collection
      get 'paper-signs', as: :paper_signs, on: :collection
      get 'search', on: :collection
    end
    resources :job_applications, except: [:edit]
    resources :passes, controller: 'tickets', free: true, except: [:show, :edit] do
      get 'link', on: :collection
    end
    resources :packages do
      get 'vendors', on: :collection
    end
    resources :prizes
    resources :shifts, except: [:new, :edit] do
      get 'schedule', on: :collection
      get 'timesheet', on: :collection
    end
    resources :signs
    resources :tickets, except: [:show, :edit]
  end
  resources :subscriptions, except: [:edit] do
    post 'pay', on: :member
  end
  resources :texts, except: [:edit, :update, :destroy] do
    get 'conversations', on: :collection
  end
  resources :transfers, except: [:show, :edit, :update]
  resources :users, concerns: [:card_owner], except: [:index] do
    get 'login', on: :member
  end
  resources :vendors, concerns: [:card_owner], shallow: true do
    resources :contacts, controller: 'users', only: [:new, :create]
    resources :offers, except: [:show, :new, :edit]
    resources :payments, only: [:new, :create]
    resources :testimonials, except: [:show, :new, :edit]
    get 'merge', on: :member
    post 'merge', action: 'merge_into', on: :member
  end

  get 'search(/:filter)' => 'search#index', :as => :search
  get 'settings' => 'settings#index', :as => :settings
  post 'preview' => 'settings#preview'

  post 'webhooks/stripe' => 'webhooks#stripe'
  post 'webhooks/twilio' => 'webhooks#twilio'


  get 'user_email' => 'users#user_email'
  get 'sync_cm_task' => 'users#sync_cm_task'
  get 'get_staff_list' => 'users#get_staff_list'

  #resources :staffs

end

app/models/booth.rb
class Booth < ActiveRecord::Base
  enum payment_method: [:card, :check, :cash, :trade]
  enum payment_schedule: [:full, :deposit, :monthly]
  enum status: [:pending, :approved, :denied]

  belongs_to :show, required: true
  belongs_to :vendor, required: true
  belongs_to :card
  belongs_to :coordinate, dependent: :destroy
  has_many :add_ons, dependent: :delete_all
  has_many :fees, dependent: :delete_all
  has_many :payments, as: :payable
  belongs_to :sign

  accepts_nested_attributes_for :add_ons, allow_destroy: true
  accepts_nested_attributes_for :coordinate

  validates_associated :add_ons
  validates_presence_of :payment_method
  validates_presence_of :payment_schedule
  validates_inclusion_of :size, in: Config.booths.keys, allow_nil: true
  validates_numericality_of :free_pass_limit, greater_than: 0
  validates_uniqueness_of :sign_id, scope: :show_id, allow_nil: true
  validate :add_ons_are_valid

  before_create :mark_vendor_as_sold
  before_save :calculate_total
  before_save :attach_sign, if: :status_changed?
  after_update :send_welcome_text, if: :checked_in_at_changed?
  before_destroy :nullify_payments
  after_destroy :destroy_coordinate
  strip_attributes only: [:size]

  scope :flagged, -> {where(flagged: true)}
  scope :visible, -> {where(visible: true)}
  scope :with_add_on, ->(add_on_type) {joins(:add_ons).where("add_ons.type = ?", add_on_type)}
  scope :with_balance, -> {where("balance > 0")}
  scope :with_bag, -> {joins(:add_ons).where("add_ons.type = 'bag_promo'")}
  scope :with_industries, -> {where("ARRAY_LENGTH(industries, 1) > 0")}
  scope :with_sign, -> {joins(:add_ons).where("add_ons.type = 'sign'")}
  scope :with_size, -> {where.not(size: nil)}
  scope :without_size, -> {where(size: nil)}

  def to_s
    (size ? "#{size} Booth" : (bag_promo? ? "Bag Promo"  : "Empty Application")) + " - " + show.date.to_s(:mth_yr)
  end

  def bag_promo?
    add_ons.where(type: 'bag_promo').count > 0
  end
  alias :bag? :bag_promo? # bag? is deprecated, use bag_promo?

  def editable?
    if self.new_record?
      true
    else
      Date.today < show.payment_deadline
    end
  end

  # Recalculates the total due based on the booth size and add-ons.
  def calculate_total
    sub_total = 0

    if size
      sub_total += Config.booths[size][:price]
    end

    self.add_ons.each do |add_on|
      sub_total += add_on.total
    end
    sub_total += industries.length * 35000
    sub_total += fees.pluck(:amount).reduce(0, &:+)

    self.total = sub_total
    self.balance = total - payments.paid.map(&:amount_paid).reduce(0, &:+)
    self
  end

  def door
    coordinate && Config.sections[coordinate.section]
  end

  def has_add_on?(type, value=nil)
    a = add_ons.where(type: type)
    a = a.where(value: value) if value
    a.count > 0
  end

  def line_items
    items = []

    if size && details = Config.booths[size]
      items << {type: "booth", title: details[:name] + " Booth", price: details[:price]}
    end

    add_ons.each do |add_on|
      add_on && add_on.price > 0 && items << { type: "add_on", title: add_on.to_s,
        price: add_on.price, quantity: add_on.quantity }
    end
    industries.each { |ind| items << { type: "industry", title: "Extra Industry (#{ind.titleize})", price: 35000 } }
    fees.each { |fee| items << { type: "fee", title: fee.description, price: fee.amount, id: fee.id } }

    items
  end

  def payment_deadline
    if created_at > show.date - 30.days
      created_at.to_date
    elsif card?
      show.date - 30.days
    else
      created_at.to_date + 30.days
    end
  end

  private
    def attach_sign
      self.sign = approved? && has_add_on?("sign") ? vendor.signs.unused(show_id).order("back DESC, id DESC").limit(1).first : nil
    end

    def destroy_coordinate
      coordinate && coordinate.delete
    end

    def nullify_payments
      payments.scheduled.delete_all
      payments.update_all(payable_id: nil, payable_type: nil)
    end

    def add_ons_are_valid
      industries&.reject!(&:blank?)

      if industries.include?(vendor&.industry)
        errors.add(:industries, "can't include vendor's default industry")
      elsif industries.include?("photography")
        errors.add(:industries, "can't include photography")
      end
    end

    def mark_vendor_as_sold
      statuses = vendor.show_statuses.merge(show_id.to_s => "sold")
      vendor.update_column("show_statuses", statuses)
    end

    def send_welcome_text
      return unless vendor.cell_phone
      Text.create(recipient: vendor, message: "Hello! Thanks for being part of The Wedding Expo. Use this text number for any questions or concerns you have, it's the quickest way for us to help you.")
    end
end

app/controllers/booths_controller.rb
class BoothsController < BaseController
  include Pdf

  protect_from_forgery except: :update
  before_action :set_booth, only: [:show, :edit, :update, :destroy, :addons, :billing]
  before_action :set_show, only: [:index, :new, :create, :paper_signs, :door, :search]
  layout "booth", only: [:show, :edit, :addons, :billing]

  # GET /booths
  # GET /booths.json
  def index
    @booths = @current_show.booths.select("booths.*, COUNT(payments.*) AS scheduled_payment_count")
      .joins("LEFT JOIN payments ON payments.payable_type = 'Booth' AND payments.payable_id = booths.id AND payments.status = 6")
      .where.not(status: 2).group("booths.id").order("status ASC, updated_at DESC")
    @pending = @current_show.booths.pending.count
    @denied = @current_show.booths.denied.preload(:vendor)
    @booths = @booths.preload(:add_ons, :coordinate, :sign, :vendor => :storefront_address)
    @count = @current_show.booths.approved.count
    @add_ons = Hash[@booths.map { |b| [b.id, Hash[b.add_ons.map { |a| [a.type, a.to_s.escape_csv] }]] }]
  end

  # GET /shows/1/booths/7.json
  def door
    section_map = Hash.new
    Config.sections.each { |k, v| section_map[v.to_s] ||= Array.new; section_map[v.to_s] << k }
    valid_sections = section_map[params[:door]]
    @booths = @current_show.booths.joins(:coordinate, :vendor).approved.
      where("coordinates.section in (?)", valid_sections).order("vendors.name").
      preload(:add_ons, :coordinate, :sign, :vendor)
    render :index
  end

  # GET /shows/1/booths/search.json
  def search
    @booths = @current_show.booths.joins(:vendor).approved.
      where("vendors.name ILIKE ?", "%#{params[:query]}%").order("vendors.name").
      preload(:add_ons, :coordinate, :sign, :vendor)
    render :index
  end

  # GET /booths/paper-signs.pdf
  def paper_signs
    booths_without_signs = @current_show.booths.approved.where(sign: nil).preload(:vendor)
    pdf = paper_signs_pdf(booths_without_signs)
    send_data(pdf.render, disposition: 'inline', filename: 'paper_signs.pdf')
  end

  # GET /booths/1
  # GET /booths/1.json
  def show
  end

  # GET /booths/1/addons
  def addons
    @add_ons = @booth.add_ons.order(:created_at)
    @add_ons = [@booth.add_ons.new(type: :bag_promo)] if @booth.add_ons.empty?
  end

  # GET /booths/1/billing
  def billing
    @payments = Payment.where(payable: @booth).order("scheduled_for ASC, captured_at DESC").preload(:card)
    @pending_balance = @booth.balance - @payments.scheduled.sum(:amount)
  end

  # GET /booths/1/edit
  def edit
  end

  # GET /booths/new
  def new
    @booth = Booth.new
  end

  # POST /booths
  # POST /booths.json
  def create
    @booth = Booth.new(booth_params)
    @booth.show = @current_show

    respond_to do |format|
      if @booth.save
        format.html { redirect_to @booth, notice: "Booth was successfully created." }
        format.json { render :show, status: :created, location: @booth }
      else
        format.html { render :new }
        format.json { render json: @booth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booths/1
  # PATCH/PUT /booths/1.json
  def update
    return render(:edit) unless @booth.update(booth_params)
    redirect = request.referer || booth_path(@booth)
    respond_to do |format|
      format.html { redirect_to redirect, notice: "Booth was successfully updated." }
      format.json { render :show, status: :ok, location: @booth }
    end
  end

  # DELETE /booths/1
  # DELETE /booths/1.json
  def destroy
    respond_to do |format|
      if @booth.destroy
        format.html { redirect_to booths_url, flash: { warning: "Booth was deleted." } }
      else
        msg = if @booth.errors.present?
          @booth.errors.full_messages.join(".\n") + "."
        else "Booth could not be deleted." end
        format.html { redirect_to @booth, alert: msg }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booth
      @booth = Booth.find(params[:id])
      @inactive_show = @booth.show
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booth_params
      params.require(:booth).permit(:vendor_id, :status, :section_requested, :size, :requests, :payment_method, :checked_in_at,
        :payment_schedule, :card_id, :coordinate_id, :sign_id, :visible, :leads_access, :flagged, :received_marketing, :free_pass_limit,
        :industries => [], :coordinate_attributes => [:id, :x, :y, :a, :section], :add_ons_attributes => [:_destroy, :id, :type, :value, :quantity, :price, :description])
    end
end

app/views/booths/_form.haml
- show_errors_for(@booth)

= form_for(@booth, builder: FormBuilder) do |f|
  = f.hidden_field(:status)
  .row
    .small-7.columns
      = f.text_group :vendor_id, spellcheck: false
      .row
        = f.select_col :size, 6, booth_sizes, include_blank: true
        = f.fields_for(:coordinate, @booth.coordinate) do |coordinate_fields|
          = coordinate_fields.select_col :section, 6, Config.sections.keys, include_blank: true
      - unless @booth.new_record?
        = f.select_group :sign_id, @booth.vendor.signs.map{ |s| [s.text, s.id] }, include_blank: true
      = f.text_area_group :requests
      .row
        = f.select_col :payment_method, 6, Booth.payment_methods.keys
        = f.select_col :payment_schedule, 6, Booth.payment_schedules.keys, col: 'end'
      .row
        = f.switch_col :leads_access, 4
        = f.switch_col :visible, 4, col: 'end'
        - if @booth.bag?
          = f.switch_col :received_marketing, 4, col: 'end'

  %button.button Save
  - unless @booth.approved?
    %button.button.success(onclick="document.getElementById('booth_status').value = 'approved';") Approve & Save
  - unless @booth.denied?
    %button.button.alert(onclick="document.getElementById('booth_status').value = 'denied';") Deny & Save
  = delete_link(@booth)

:javascript
  new TokenField(id('booth_vendor_id'), '#{search_path(:vendors, :json)}', {values: [#{@booth.vendor.as_json(only: :id, methods: :to_s).to_json}]})

app/views/booths/addons.haml
- show_errors_for(@booth)

= form_for(@booth, builder: FormBuilder) do |f|
  %table#add-on-table
    %thead
      %tr
        %th Add-on
        %th Type (optional)
        %th(width="110") Quantity
        %th(width="140") Price
        %th(width="50") Del
    %tbody
      = f.fields_for(:add_ons, @add_ons) do |add_on_fields|
        %tr
          %td= add_on_fields.select(:type, Config.add_ons.keys, {}, class: 'skinny')
          %td
            - if add_on_fields.object.config.has_key?(:values)
              = add_on_fields.select(:value, add_on_fields.object.config[:values], {}, class: 'skinny')
            - else
              \--
          %td= add_on_fields.select(:quantity, (1..3), {}, class: 'skinny')
          %td= number_to_currency(add_on_fields.object.price / 100.0)
          %td
            - if add_on_fields.object.persisted?
              = add_on_fields.check_box(:_destroy)
            - else
              \--
  %button.button Save
  %a.new-add-on.button-link.success New add-on

app/views/booths/billing.haml
.row
  .small-3.columns
    %label Total
    %p= number_to_currency(@booth.total / 100.0)
  .small-3.columns.end
    %label Balance
    %p= number_to_currency(@booth.balance / 100.0)
  .small-3.columns.end
    %label Method
    %p= @booth.payment_method.humanize
  .small-3.columns.end
    %label Schedule
    %p= @booth.payment_schedule.humanize
.row
  .small-6.columns
    %label
      Cost Breakdown
      = link_to('+', new_booth_fee_path(@booth))
    %table
      %thead
        %tr
          %th(width="190") Item
          %th(width="90") Cost
          %th
      %tbody
        - @booth.line_items.each do |item|
          %tr
            %td= item[:title]
            %td= number_to_currency(item[:price] / 100.0).chomp('.00')
            %td.action
              - if item[:id]
                = link_to('Delete', fee_path(item[:id]), method: 'delete', data: { confirm: 'Are you sure you want to delete this line item?' })
  .small-6.columns
    %label
      Payments
      = link_to('+', new_booth_payment_path(@booth))
    %table
      %thead
        %tr
          %th Amount
          %th Method
          %th Status
          %th Date
      %tbody
      - @payments.each do |payment|
        %tr.link(data-href="#{payment_path(payment)}" title="#{payment.description}")
          %td= number_to_currency(payment.amount / 100.0).chomp('.00')
          %td
            - if payment.card? && payment.card
              = payment.card.brand.to_s.sub('American Express', 'Amex') + ' ' + payment.card.last4.to_s
            - else
              = payment.method.titleize
          %td= payment.paid? && payment.refund_amount > 0 ? 'Partial Refund' : payment.status.titleize
          %td.right
            - if payment.scheduled?
              %i.octicon.octicon-primitive-dot.warning(title="Created at #{payment.created_at}")
              = payment.scheduled_for
            - else
              = payment.captured_at&.to_date

app/views/booths/edit.haml
= render 'form'

app/views/booths/index.csv.erb
Vendor, Industry, Rewards Status, Booth Status, Size, Cell Phone, Storefront Address, Storefront City, Storefront State, Storefront Zip, <%= Config.add_ons.map { |k, v| v[:name] }.join(', ') %>
<% @booths.each do |booth| %>
<%= booth.vendor.name.escape_csv %>,<%= booth.vendor.industry %>,<%= booth.vendor.rewards_status %>,<%= booth.status %>,<%= booth.size %>,<%= number_to_phone(booth.vendor.cell_phone) %>,<%= booth.vendor.storefront_address&.street&.escape_csv %>,<%= booth.vendor.storefront_address&.city&.escape_csv %>,<%= booth.vendor.storefront_address&.state %>,<%= booth.vendor.storefront_address&.zip %>,<%= Config.add_ons.map { |k, v| @add_ons[booth.id][k] }.join(', ') %>
<% end %>

app/views/booths/index.haml
= content_for(:title, 'Booths')
= content_for(:actions) do
  %li.action.inline= link_to(icon(:document_plus), new_booth_path, class: "icon", title: "New booth")
  %li.action.inline= link_to(icon(:file_type_table), request.path + ".csv", class: "icon", title: "Download CSV")
  %li.action.inline= link_to(icon(:printer), paper_signs_show_booths_path(format: :pdf), class: "icon", title: "Print paper signs")
  %li.action.inline= link_to(icon(:map), "/map", class: "icon", title: "Open map", target: "_blank")
= content_for(:count, @count.to_s)

%table.sort(data-cycle-col="7")
  %thead
    %tr
      %th(width="18" data-sort-none)
      %th(width="242") Vendor
      %th(width="160") Industry
      %th(width="90") Size
      %th(width="100") Section
      %th(width="140" data-sort-as="int" data-sort-reverse) Paid/Balance
      %th(width="240" data-sort-as="custom" data-sort-reverse) Modified
      %th Sign
      %th(data-sort-reverse) Bag Promo
      %th Payment
  %tbody
    = fold("pending booth", @pending)
    - @booths.each do |booth|
      %tr.link(height="39px" data-href="#{booth_path(booth)}" class="#{'folded' if booth.pending?}")
        %td
          - if booth.pending?
            %i.octicon.octicon-primitive-dot.warning(title="Pending since #{booth.created_at}")
          - elsif booth.denied?
            %span.alert x
        %td= booth.vendor
        %td= booth.vendor.industry.titleize
        %td= booth.size || '--'
        %td= booth.coordinate.section if booth.coordinate
        %td
          - if booth.pending?
            \--
          - else
            %span>= number_to_currency((booth.total - booth.balance) / 100.0).chomp('.00')
            %span= '/' + number_to_currency(booth.balance / 100.0).chomp('.00')
        %td(data-sort-by="#{booth.updated_at.to_i}")= booth.updated_at
        %td= booth.sign_id ? link_to(booth.sign, sign_path(booth.sign_id), title: booth.sign.text) : badge('Needs sign', 'radius secondary') if @add_ons[booth.id]['sign']
        %td
          - if @add_ons[booth.id]['bag_promo'] && booth.received_marketing
            = badge('Received', 'radius success')
          - elsif @add_ons[booth.id]['bag_promo']
            = badge('Waiting', 'radius secondary')
        %td
          - if booth.card?
            = booth.card_id ? "Card" : 'Card [none on file]'
          - else
            = booth.payment_method.titleize
    = fold("denied booth", @denied.length, class: 'alert')
    - @denied.each do |booth|
      %tr.disabled.link(height="39px" data-href="#{booth_path(booth)}" class="folded")
        %td
          %strong.alert(title="Denied") &times;
        %td= booth.vendor
        %td
        %td
        %td
        %td
        %td
        %td
        %td
        %td

app/views/booths/new.haml
= content_for(:title, 'New Booth')

= render 'form'

app/views/booths/show.haml
.row
  .small-6.columns
    %label Vendor
    %p= link_to(@booth.vendor, @booth.vendor)
  .small-3.columns
    %label Status
    %p= @booth.status.humanize
  .small-3.columns
    %label Size
    - if @booth.size
      %p #{@booth.size} #{Config.booths[@booth.size][:title]}
    - else
      %p None
.row
  .small-3.columns
    %label Add-ons
    %ul
      - @booth.add_ons.order(:type).each do |add_on|
        %li= add_on
      - @booth.industries.each do |ind|
        %li Industry (#{ind.humanize.downcase})
  .small-3.columns
    %label Sign
    %p= @booth.sign ? link_to(@booth.sign, @booth.sign, title: @booth.sign.text) : 'No'
  .small-6.columns.end
    %label Requests
    %p= @booth.requests