config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  concern :card_owner do
    resources :cards, except: [:edit, :update]
  end

  resources :articles, except: [:edit]
  resources :locations
  resources :payments, only: [:index]
  resources :points
  resources :positions, except: [:edit]
  resource :session, path: 'login', except: [:show, :new, :edit] do
    get '/', action: 'new', on: :collection, as: :new
  end
  resources :shows, shallow: true do
    resources :attendees, controller: 'users'
    resources :staffs
    resources :booths, shallow: true do
      resources :fees, only: [:new, :create, :destroy]
      resources :payments, except: [:index, :edit] do
        post 'pay', on: :member
      end
      get 'addons', on: :member
      get 'billing', on: :member
      get ':door', action: 'door', door: /[0-9A-Z]/, on: :collection
      get 'paper-signs', as: :paper_signs, on: :collection
      get 'search', on: :collection
    end
    resources :job_applications, except: [:edit]
    resources :passes, controller: 'tickets', free: true, except: [:show, :edit] do
      get 'link', on: :collection
    end
    resources :packages do
      get 'vendors', on: :collection
    end
    resources :prizes
    resources :shifts, except: [:new, :edit] do
      get 'schedule', on: :collection
      get 'timesheet', on: :collection
    end
    resources :signs
    resources :tickets, except: [:show, :edit]
  end
  resources :subscriptions, except: [:edit] do
    post 'pay', on: :member
  end
  resources :texts, except: [:edit, :update, :destroy] do
    get 'conversations', on: :collection
  end
  resources :transfers, except: [:show, :edit, :update]
  resources :users, concerns: [:card_owner], except: [:index] do
    get 'login', on: :member
  end
  resources :vendors, concerns: [:card_owner], shallow: true do
    resources :contacts, controller: 'users', only: [:new, :create]
    resources :offers, except: [:show, :new, :edit]
    resources :payments, only: [:new, :create]
    resources :testimonials, except: [:show, :new, :edit]
    get 'merge', on: :member
    post 'merge', action: 'merge_into', on: :member
  end

  get 'search(/:filter)' => 'search#index', :as => :search
  get 'settings' => 'settings#index', :as => :settings
  post 'preview' => 'settings#preview'

  post 'webhooks/stripe' => 'webhooks#stripe'
  post 'webhooks/twilio' => 'webhooks#twilio'


  get 'user_email' => 'users#user_email'
  get 'sync_cm_task' => 'users#sync_cm_task'
  get 'get_staff_list' => 'users#get_staff_list'

  #resources :staffs

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  enum method: [:card, :check, :cash, :trade, :credit]
  enum status: [:paid, :refunded, :declined, :disputed, :lost, :won, :scheduled]

  belongs_to :card
  belongs_to :payer, polymorphic: true, required: true
  belongs_to :payable, polymorphic: true

  validates_numericality_of :amount, greater_than_or_equal_to: 100
  validates_presence_of :description
  validate :method_and_card_match, on: :create
  validate :refund_amount_is_positive
  validate :scheduled_for_is_future, if: :scheduled_for?, on: :create
  validate :scheduled_for_includes_card, if: :scheduled_for?, on: :create

  before_create :process, if: :card?
  before_create -> { self.captured_at = Time.now }, unless: :card?
  after_create -> { payable&.save! }, if: :paid?
  before_update :refund, if: :refund_amount_changed?
  after_destroy -> { payable&.save! }, if: :paid?

  def charge_now!(options = {})
    return false if stripe_charge_id != nil
    begin
      charge = Stripe::Charge.create(
        :capture => true,
        :amount => amount,
        :currency => 'usd',
        :customer => card.owner.stripe_customer_id,
        :source => card.stripe_card_id,
        :description => description
      )
      self.stripe_charge_id = charge.id
      self.status = :paid
    rescue Stripe::CardError, Stripe::InvalidRequestError => e
      self.stripe_charge_id = e.json_body[:error][:charge]
      self.status = :declined
      self.reason = e.message
      errors.add(:base, e.message.chop)
    end

    self.captured_at = Time.now
    self.scheduled_for = nil
    save(validate: false) and payable&.save! if options[:save]
  end

  # Returns the net amount that has been collected from the payer.
  def amount_paid
    (amount - refund_amount if paid? || won?).to_i
  end

  def refundable?
    !new_record? && refund_amount < amount && %q(paid refunded won).include?(status)
  end

  private
    # Callbacks
    def process
      if scheduled_for
        self.status = :scheduled
        return
      elsif stripe_charge_id != nil
        return
      elsif card
        charge_now!
      else
        errors.add('Card', 'is required for this payment method')
        throw(:abort)
      end
    end

    def refund
      self.status = :refunded if refund_amount == amount
      if method == 'card'
        Stripe::Refund.create(charge: stripe_charge_id, amount: refund_amount)
      end
      payable.increment!(:balance, refund_amount - refund_amount_was) if payable&.respond_to?(:balance)
    end

    # Validations
    def method_and_card_match
      if method != 'card' && card_id != nil
        errors.add(:method, 'must be card if a card is selected')
      end
    end

    def refund_amount_is_positive
      return unless amount
      if refund_amount < refund_amount_was
        errors.add(:refund_amount, 'can\'t be lower than previous value')
      elsif refund_amount > amount
        errors.add(:refund_amount, 'is greater than amount paid')
      end
    end

    def scheduled_for_is_future
      errors.add(:scheduled_for, 'must be in the future') if scheduled_for <= Date.today
    end

    def scheduled_for_includes_card
      errors.add(:card, 'is required to schedule payment') if method != 'card' || card_id == nil
    end
end

app/controllers/payments_controller.rb
class PaymentsController < BaseController
  before_action :set_payment, only: [:show, :update, :destroy, :pay]

  # GET /payments
  def index
    @payments = Payment.where("payer_type = 'Vendor' AND captured_at > ? OR status = 6", Date.today - 60.days)
      .order("scheduled_for ASC, captured_at DESC")
    @scheduled = Payment.where(status: 6).count
    @payments.preload!(:payer).preload!(:card)
  end

  # GET /payments/1
  def show
    @editable = @payment.scheduled? && @payment.scheduled_for != nil
  end

  # GET /payments/new
  def new
    if params[:booth_id]
      @payable = @booth = Booth.find(params[:booth_id])
      @payer = @booth.vendor
      @payment = Payment.new(payable: @booth, payer: @payer, amount: @booth.balance)
    else
      @payer = Vendor.find(params[:vendor_id])
      @payment = Payment.new(payer: @payer, amount: 0)
    end
    @editable = true
  end

  # POST /payments
  # POST /payments.json
  def create
    params[:payment][:amount].gsub!(/[$,]/, "")
    params[:payment][:amount] = (params[:payment][:amount].to_f * 100).to_i
    @payment = Payment.new(payment_params)

    if params[:booth_id]
      @payable = @booth = Booth.find(params[:booth_id])
      @payer = @booth.vendor
    else
      @payer = Vendor.find(params[:vendor_id])
    end

    @payment.payer = @payer
    @payment.payable = @payable

    if @payment.save
      if @payment.errors.empty?
        redirect_to(@payment.payable || @payment.payer, notice: "Payment was successfully created.")
      else
        redirect_to(@payment.payable || @payment.payer, alert: @payment.errors.full_messages.join(".\n") + ".")
      end
    else
      @editable = true
      render(:new)
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    [:amount, :refund_amount].each do |a|
      next unless params[:payment].has_key?(a)
      params[:payment][a].gsub!(/[$,]/, "")
      params[:payment][a] = (params[:payment][a].to_f * 100).to_i
    end

    respond_to do |format|
      if @payment.update(payment_params)
        # format.html { redirect_to :payments, notice: "Payment was successfully updated." }

        # Redirect to the show path
        format.html { redirect_to payment_path(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        @editable = true
        format.html { render :show }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to :payments, flash: { warning: "Payment was deleted." } }
      format.json { head :no_content }
    end
  end

  # POST /payments/1/pay
  def pay
    if @payment.charge_now!(save: true)
      redirect_to :payments, notice: "Payment was successfully paid."
    else
      redirect_to :payments, flash: {alert: "Failed to pay payment."}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :refund_amount, :description, :method, :card_id, :scheduled_for)
    end
end

app/views/payments/_form.haml
- show_errors_for(@payment)

= form_for(@payable ? [@payable, @payment] : [@payer, @payment], builder: FormBuilder) do |f|
  %p
    %label For
    = link_to(@payment.payer, @payment.payer)
    %br
    - if @payment.payable
      = link_to(@payment.payable, @payment.payable)

  = f.text_group :amount, value: number_to_currency(@payment.amount / 100.0), disabled: !@editable
  - if @payment.refundable? || @payment.refund_amount > 0
    = f.text_group :refund_amount, value: number_to_currency(@payment.refund_amount / 100), col: 'end', disabled: @payment.refund_amount == @payment.amount

  = f.text_group :description

  = f.select_group :method, Payment.methods.keys, {selected: @payment.new_record? ? @payment.payable&.payment_method : @payment.method}, disabled: !@editable
  - if @payment.payer.cards.empty?
    %p No card on file.
  - else
    = f.select_group :card_id, @payment.payer.cards.map {|c| ["#{c.brand} #{c.last4} - #{c.expiry.to_s(:expiry)}", c.id]}, {include_blank: true}, disabled: !@editable

  - if @editable
    = f.date_group(:scheduled_for, start_year: Date.today.year, include_blank: true)

  %button.button#save Save
  - if @editable && !@payment.new_record?
    = link_to('Pay now', pay_payment_path(@payment), class: 'button-link success', method: 'post')
    = link_to('Delete', @payment, class: 'button-link alert', method: 'delete', data: {confirm: 'Delete this payment?'})

:javascript
  document.getElementById('new_payment').addEventListener('submit', function(e) {
    if (document.getElementById('payment_method').value == 'card' && document.getElementById('payment_scheduled_for_1i').value == '')
      confirm('Charge card now?') || e.preventDefault();
  });

app/views/payments/index.haml
= content_for(:title, "Payments")

%table
  %thead
    %tr
      %th(width="220") Payer
      %th(width="130") Amount
      %th(width="150") Method
      %th(width="130") Status
      %th(width="210") Description
      %th(width="150") Date
  %tbody
    = fold("scheduled payment", @scheduled)
    - @payments.each do |payment|
      %tr{ data: { href: payment_path(payment) }, class: "#{'folded' if payment.scheduled?} #{payment.declined? ? 'canceled' : 'link'}" }
        %td= payment.payer
        %td= number_to_currency(payment.amount / 100.0).sub(".00", "")
        %td
          - if payment.card? && payment.card
            = payment.card.brand.sub("American Express", "Amex") + " " + payment.card.last4
          - else
            = payment.method.titleize
        %td= payment.paid? && payment.refund_amount > 0 ? "Partial Refund" : payment.status.titleize
        %td= payment.description
        %td
          - if payment.scheduled?
            %i.octicon.octicon-primitive-dot.warning(title="Created at #{payment.created_at}")
            = payment.scheduled_for
          - else
            = payment.captured_at

app/views/payments/new.haml
- set_container(:small)
= content_for(:title, 'New Payment')

= render 'form'

app/views/payments/show.haml
- set_container(:small)
= content_for(:title, 'Edit Payment')

= render 'form'